baseURL = 'https://bytetrail.dev/'
languageCode = 'en-us'
title = 'Byte Trail Dev'
theme = 'beautifulhugo'

[Params]
#  homeTitle = 'Beautiful Hugo Theme' # Set a different text for the header on the home page
  subtitle = 'Build a beautiful and simple website in minutes'
  mainSections = ['post','posts']
  logo = 'img/avatar-icon.png' # Expecting square dimensions
  favicon = 'img/favicon.ico'
  commit = false
  rss = false
  hideAuthor = true
  comments = false
  readingTime = false
  wordCount = false
  useHLJS = false
  socialShare = false
  delayDisqus = false
  showRelatedPosts = false


[Params.author]
  # Set only your 'username' for default hosts and full URLs otherwise (e.g., 'https://MyGitLab.org/username')
  name = 'Brandan Waldvogel'
  email = 'contact@bytetrail.dev'
  github = 'bytetraildev'



